### PR TITLE
Add google as a default geocoder service

### PR DESCRIPTION
**Pull request by dp6ai**

### CODE REVIEW

**Comment by michelson** [comment]
hi @dp6ai did you test this ?

**Comment by dp6ai** [comment]
I assumed it would work because it looks like an obvious change BUT

```irb(main):001:1* GEOCODER_SERVICES = [
irb(main):002:2*   {
irb(main):003:2*     name: :ipinfo_io,
irb(main):004:2*     api_key: ENV['GEOCODER_API_KEY'],
irb(main):005:2*     timeout: 2
irb(main):006:1*   },
irb(main):007:2*   {
irb(main):008:2*     name: :google,
irb(main):009:2*     api_key: ENV['GEOCODER_API_KEY'],
irb(main):010:2*     timeout: 2
irb(main):011:1*   },
irb(main):012:2*   { name: :maxmind_local,
irb(main):013:1*     file: File.join(Rails.root, 'vendor/data', 'GeoLiteCityv6.dat') },
irb(main):014:2*   {
irb(main):015:2*     name: :test
irb(main):016:1*   }
irb(main):017:0> ]
=> [{:name=>:ipinfo_io, :api_key=>"XXXXXXXXX", :timeout=>2}, {:name=>:google, :api_key...
irb(main):018:0>
irb(main):019:0>
irb(main):020:0>
irb(main):021:1* DEFAULT_GEOCODER_SERVICE = GEOCODER_SERVICES.find do |o|
irb(main):022:1*   o[:name].to_s === (ENV['DEFAULT_GEOCODER_SERVICE'] || (Rails.env.test? ? 'test' : 'maxmind_local'))
irb(main):023:0> end
=> {:name=>:google, :api_key=>"YYYYYYYYY", :timeout=>2}
irb(main):024:0>
```
and i'm still getting this:

```2021-06-22T20:49:29.207022+00:00 heroku[router]: at=info method=POST path="/api/graphql" host=support-staging.blam.com request_id=4e78cb81-67ff-4c2b-b281-f0cd29a03e52 fwd="82.0.253.85" dyno=web.1 connect=0ms service=27ms status=200 bytes=1134 protocol=https
2021-06-22T20:49:29.295565+00:00 app[web.1]: Google API error: request denied (You must use an API key to authenticate each request to Google Maps Platform APIs. For additional information, please refer to http://g.co/dev/maps-no-account).
```

**Comment by dp6ai** [comment]
Where are you calling geocoder? I'm struggling to see where it happens

**Comment by dp6ai** [comment]
@michelson I'm happy to do some more testing on this but i cant work out how the geocoder is being used or when its called, if you can point me in the right direction ill debug

**Comment by michelson** [comment]
hey @dp6ai thanks for your contribution here, really appreciated, please look at the file https://github.com/chaskiq/chaskiq/blob/master/config/initializers/geocoder_request.rb

**Comment by dp6ai** [comment]
OK. Finally worked out the issue. Geocoder doesn't offer google for [IP lookup ](https://github.com/alexreisner/geocoder/blob/master/README_API_GUIDE.md#ip-address-lookups) using:
`DEFAULT_GEOCODER_SERVICE=ipinfo_io` and a valid access token worked. 

(Maybe add this to the docs and close this PR?)

Thanks

**Pull request closed without merging**
